### ISSUE TITLE
crash on exit 

### ISSUE THREAD

**Issue by moshiplus** [jlouage/flutter-carousel-pro#12]
hi .
crash on exit because `PageController` not disposed .
here the log 
`[ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter ( 2562): 'package:flutter/src/widgets/page_view.dart': Failed assertion: line 96 pos 7: 'positions.isNotEmpty': PageController.page cannot be accessed before a PageView is built with it.
E/flutter ( 2562): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:37:39)
E/flutter ( 2562): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:33:5)
E/flutter ( 2562): #2      PageController.page (package:flutter/src/widgets/page_view.dart)
E/flutter ( 2562): #3      CarouselState.initState.<anonymous closure> (package:carousel_pro/src/carousel_pro.dart:110:24)
E/flutter ( 2562): #4      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter ( 2562): #5      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter ( 2562): #6      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

`

**Comment by shashikantx** [comment]
Check https://github.com/jlouage/flutter-carousel-pro/pull/13/commits/a48ef8ad587ed24c86310c6cbbc45a3afdbd2d16

**Comment by Yididya** [comment]
Anyone accepting this pull request @jlouage
