### ISSUE TITLE
Can you add a license that will allow others to use this nice repo

### ISSUE THREAD

**Issue by nlacey** [jlouage/flutter-carousel-pro#18]
I was excited to test out this repo until I saw the license.

I'm not sure how other people are legally using your repo including the 15 forks
since it's "All rights reserved."

Maybe I'm just mis-understanding copy right law

Thanks for the hard work you did creating this project!

**Comment by tscholze** [comment]
If you need some inspiration, maybe the following side could help you. :) [https://choosealicense.com/](https://choosealicense.com/)

**Comment by jlouage** [comment]
I will update the licenses you can use it.

**Comment by tscholze** [comment]
Nice, thanks buddy!

**Comment by joelalcedo** [comment]
Are there plans to add a licence to this plugin?
