### ISSUE TITLE
How to set image from API into Carousel Pro?

### ISSUE THREAD

**Issue by rrifafauzikomara** [jlouage/flutter-carousel-pro#37]

**Comment by rrifafauzikomara** [comment]
Any idea to set Image from API into this library?

**Comment by rbocchi** [comment]
Hi,

I'm using [Flutter Bloc](https://pub.dev/packages/flutter_bloc) package, which makes implementing BLoC design pattern a lot easier, more details about it you can see in the [documentation](https://felangel.github.io/bloc/#/).

In my app, I need to get a list of banners, where each one has an id and an image url, so my model is: 
```
class Banner extends Equatable {
  final String id;
  final String image;

  Banner({this.id, this.image}) : super([id, image]);
}
```
When the application [state](https://felangel.github.io/bloc/#/coreconcepts?id=states) is BannersLoaded, I have the list of banners obtained from my API, and assign the images to carousel as follows:

```
if (state is BannerLoaded) {
          ...
          List _imgs = List<NetworkImage>();
          state.banners.forEach((b) {
            _imgs.add(NetworkImage(b.image));
          });
          return Container(
            child: Carousel(
                autoplay: true,
                autoplayDuration: Duration(seconds: 5),
                animationCurve: Curves.fastOutSlowIn,
                animationDuration: Duration(milliseconds: 800),
                boxFit: BoxFit.cover,
                dotColor: Colors.transparent,
                dotSize: 0,
                showIndicator: false,
                images: _imgs),
          );
        }
```

I hope this helps.

Best Regards

**Comment by rrifafauzikomara** [comment]
Already answered in this post: https://stackoverflow.com/questions/57258813/how-to-set-image-from-api-to-carousel-in-flutter
