### ISSUE TITLE
Infinite loop not working!

### ISSUE THREAD

**Issue by shashikantx** [jlouage/flutter-carousel-pro#6]
Animation gets stuck at last item, doesn't return to first element. Also items are aggressively going to next slide while sliding back to previous slide.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.5.6-pre.26, on Microsoft Windows [Version 10.0.17134.112], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[!] VS Code, 64-bit edition (version 1.25.0)
[√] Connected devices (1 available)

**Comment by ricnaaru** [comment]
Please check my thread #7
